### ISSUE TITLE
Login view

### ISSUE THREAD

**Issue by eribau** [anorangesky/wonderlust#6]
1. Make sure the user knows if it is logged in or not

>   //  If a user isn't signed in, currentUser is null
    var user = firebase.auth().currentUser;

2. FB login ID

> /* 
TODO:
Facebook enforces HTTPS and does not allow login with insecure hosts. When using Facebook in development 
mode with an http://localhost origin, you need to ensure that development mode is turned on for this 
Facebook App. In addition, sign-in will only be allowed with Facebook test accounts.

> To turn it on Before switching to live mode, you must provide both a valid Privacy Policy URL and data deletion information. https://developers.facebook.com/apps/1633620866825312/settings/basic/ 
*/

2. Email login 

3. Clean up the code (and rename appropriately)

**Comment by anorangesky** [comment]
TODO: <LoginFB/> check src/services/firebase.js 65:70 for instruction in how to 
TODO: close the modal after a successful event of 'login' or 'log out'
